import json
import re

def transliterate(word):
    mapping = {
        'ph': 'ف', 'ch': 'چ', 'sh': 'ش', 'th': 'ت', 'ae': 'آ', 'oe': 'و', 'aa': 'آ',
        'c': 'ک', 'k': 'ک', 'q': 'ک', 'x': 'کس', 'a': 'آ', 'b': 'ب', 'd': 'د',
        'e': 'ه', 'f': 'ف', 'g': 'گ', 'h': 'ه', 'i': 'ی', 'j': 'ج', 'l': 'ل',
        'm': 'م', 'n': 'ن', 'o': 'و', 'p': 'پ', 'r': 'ر', 's': 'س', 't': 'ت',
        'u': 'و', 'v': 'و', 'w': 'و', 'y': 'ی', 'z': 'ز'
    }
    word = word.lower()
    res = ""
    i = 0
    while i < len(word):
        if word[i:i+2] in ['ph', 'ch', 'sh', 'th', 'ae', 'oe', 'aa']:
            res += mapping[word[i:i+2]]
            i += 2
        elif word[i] == 'c':
            if i+1 < len(word) and word[i+1] in ['e', 'i', 'y']:
                res += 'س'
            else:
                res += 'ک'
            i += 1
        elif word[i] in mapping:
            res += mapping[word[i]]
            i += 1
        else:
            i += 1
    return res

manual_fixes = {
    "Eatanswill": "ایتنزویل",
    "eatberry": "توت خوراکی",
    "Ebenaceae": "آبنوسیان",
    "Ebionitic": "ابیونی",
    "ebracteolate": "بی‌برگچه",
    "ebulus": "پلم",
    "eburine": "عاجی",
    "eburnean": "عاج‌مانند",
    "eburneoid": "عاج‌وار",
    "ecad": "اکاد (ریخت سازشی)",
    "ecanda": "اکاندا",
    "ecarinate": "بی‌تیغه",
    "ecarte": "اکارته (نوعی بازی ورق)",
    "Ecaudata": "بی‌دمان",
    "eccaleobion": "ماشین جوجه‌کشی",
    "eccyclema": "اکیکلمه (در تئاتر یونان)",
    "ecdemite": "اکدمیت",
    "ecdysiast": "پوست‌انداز (در اینجا رقاصه)",
    "ecdysis": "پوست‌اندازی",
    "echelette": "اشلت (توری پراش)",
    "Echeloot": "اچلوت",
    "Echeneidae": "چسب‌ماهیان",
    "echeneidid": "چسب‌ماهی‌سان",
    "Echeneididae": "خانواده چسب‌ماهیان",
    "Echeneis": "سرده چسب‌ماهی",
    "Echidnidae": "اکیدنیده (خارپشت‌خوراکان)",
    "Echimys": "موش‌های تیغ‌دار",
    "Echinoidea": "خارپوستان (توتیاهای دریایی)",
    "Echinorhinidae": "سگ‌ماهیان خشن",
    "Echinosphaeritidae": "اکینوسفریتیان",
    "Echinostomatidae": "اکینوستوماتیده",
    "echinuliform": "خاردارشکل",
    "Echites": "اشیتس",
    "echiurid": "کرم قاشقی",
    "Echiuroidea": "کرم‌های قاشقی‌شکل",
    "Echiurus": "اشیروس",
    "ecize": "سازگار شدن با محیط",
    "eclipsareon": "ابزار نمایش کسوف",
    "eclogite": "اکلوژیت",
    "ecphonesis": "ندا (در بیان)",
    "ectad": "به سمت خارج",
    "ectiris": "بخش خارجی عنبیه",
    "Ectocarpaceae": "اکتوکارپاسه",
    "ectocinerea": "قشر خاکستری خارجی مغز",
    "ectocuniform": "استخوان میخی خارجی",
    "ectoentad": "از خارج به داخل",
    "Ectoparasitica": "انگل‌های خارجی",
    "ectoretina": "لایه خارجی شبکیه",
    "Eddaic": "ادایی (مربوط به اداها)",
    "eddyroot": "ریشه گردابی",
    "edeagra": "درد اندام تناسلی",
    "Edenize": "عدن‌گونه کردن",
    "Edentata": "بی‌دندانان",
    "edestin": "ادستین (پروتئین گیاهی)",
    "edgeman": "تیغه‌دار",
    "edh": "حرف اد (ð)",
    "Edrioasteroidea": "ادروآستروئیدها",
    "educand": "آموزش‌گیرنده",
    "Edwardsiidae": "ادواردسیده",
    "eellike": "مارماهی‌شکل",
    "eelpout": "مارماهی‌نما",
    "eelshop": "مارماهی‌فروشی",
    "eely": "مارماهی‌وار",
    "efform": "شکل دادن",
    "effund": "ریختن",
    "efoliolate": "بی‌برگچه",
    "efoveolate": "بی‌گودی",
    "eft": "سمندر",
    "eftest": "سریع‌ترین",
    "eftsoons": "بزودی",
    "egence": "نیاز",
    "egest": "دفع کردن",
    "egesta": "مواد دفعی",
    "egger": "تخم‌گذار",
    "egilops": "علف پشمکی",
    "Eglamore": "اگلامور",
    "eglatere": "نسترن",
    "egol": "ایگول",
    "egrimony": "غافث",
    "egueiite": "اگوییت",
    "Ehatisaht": "اهاتیسات",
    "eheu": "آه و افسوس",
    "Ehretiaceae": "اهرتیاسه",
    "ehuawa": "اهواوا",
    "eichbergite": "آیش‌برگیت",
    "eigne": "فرزند ارشد",
    "Eireannach": "ایرلندی",
    "eiresione": "ایرسیون (در یونان باستان)",
    "eisegesis": "تفسیر به رأی",
    "eisteddfod": "ایستدفاد (جشنواره ولزی)",
    "eisteddfodic": "مربوط به ایستدفاد",
    "eisteddfodism": "نهضت ایستدفاد",
    "ejoo": "فیبر نخل",
    "eke": "افزودن",
    "eker": "اکر",
    "ekerite": "اکریت",
    "eking": "تکمیل",
    "ekphore": "احضار خاطره",
    "ektene": "دعای پی‌در‌پی",
    "ektenes": "دعاهای پی‌در‌پی",
    "ektodynamorphic": "اکتودینامورفیک",
    "el": "حرف ال",
    "Elachistaceae": "الاکیستاسه",
    "elaeoblast": "الائوبلاست",
    "Elaeocarpaceae": "الائوکاسپاسه",
    "elaeocarpaceous": "الائوکاسپاسه-مانند",
    "elaeodochon": "غده چربی",
    "elaeosaccharum": "روغن قند",
    "elaidinic": "الائیدینیک",
    "elaioplast": "الائوپلاست",
    "elanet": "کورکور سفید",
    "Elaphomycetaceae": "الافومیستاسه",
    "Elapidae": "کفچه‌ماران",
    "Elapinae": "کفچه‌مارها (زیرخانواده)",
    "Elapsoidea": "الاپسوئیدها",
    "elasmobranch": "غضروف‌ماهی",
    "elasmobranchiate": "دارای آبشش‌های تیغه‌ای",
    "Elasmobranchii": "تیغه‌آبششان",
    "elasmothere": "الاسموتریوم",
    "Elateridae": "سوسک‌های جهنده",
    "Elatinaceae": "لاتیناسه",
    "elcaja": "الکاجا",
    "eld": "پیری",
    "Electrophoridae": "مارماهیان الکتریکی",
    "eleemosynariness": "صدقه‌دهی",
    "eleemosynary": "خیریه",
    "elemi": "المی (نوعی صمغ)",
    "eleoblast": "الئوبلاست",
    "eleomargaric": "الئومارگاریک",
    "eleostearate": "الئواستئارات",
    "eleostearic": "الئواستئاریک",
    "Elephantidae": "فیلان",
    "eleutherodactyl": "پنجه‌آزاد",
    "Eleutherodactyli": "پنجه‌آزادان",
    "eleutheromania": "شیدایی آزادی",
    "eleutheromorph": "آزادمورف",
    "eleutheropetalous": "جداگلبرگ",
    "Eleutherozoa": "آزادزیان",
    "eleutherozoan": "مربوط به آزادزیان",
    "elevon": "الون (در هواپیما)",
    "elfenfolk": "جن و پریان",
    "ellachick": "لاک‌پشت جوان",
    "elle": "او (مؤنث در فرانسه)",
    "ellenyard": "ایل‌نیارد",
    "elod": "الود",
    "Elodeaceae": "الوداسه",
    "eloge": "ستایش‌نامه",
    "elogium": "کتیبه ستایش‌آمیز",
    "Elopidae": "ده‌باله‌ماهیان",
    "elotillo": "الوتیلو",
    "els": "الس",
    "elt": "خوک ماده جوان",
    "eluvium": "الویوم (رسوب درجا)",
    "Elysiidae": "الیسیده",
    "elytriform": "بالپوش‌شکل",
    "elytrigerous": "بالپوش‌دار",
    "elytroclasia": "شکستگی بالپوش",
    "elytropolypus": "پولیپ واژینال",
    "Em": "حرف ام",
    "emajagua": "اماجاگوا",
    "emanativ": "تراوشی",
    "emarcid": "پژمرده",
    "Emballonuridae": "خفاش‌های کیسه‌بال",
    "Embden": "آمدن",
    "emberizidae": "زردپرهیان",
    "Emberizinae": "زردپره‌ها (زیرخانواده)",
    "emberizine": "مربوط به زردپره",
    "Embiidae": "امبیده",
    "Embiotocidae": "زنده‌زا‌ماهیان",
    "Emerita": "امریتا",
    "Emesa": "حمص (نام تاریخی)",
    "Emesidae": "امسیده",
    "Emm": "حرف ام",
    "emodin": "امودین",
    "empanoply": "کاملاً مسلح کردن",
    "Empetraceae": "امپتراسه",
    "Empididae": "مگس‌های رقصنده",
    "emprosthotonos": "انقباض رو به جلو",
    "Empusa": "امپوسا",
    "emu": "امو (شترمرغ استرالیایی)",
    "emyd": "لاک‌پشت برکه‌ای",
    "Emydidae": "لاک‌پشت‌های برکه‌ای",
    "Emydinae": "لاک‌پشت‌های برکه‌ای (زیرخانواده)",
    "en": "حرف ان",
    "enaena": "انائنا",
    "enalid": "گیاه دریایی",
    "Enaliornis": "انالیورنیس",
    "enamdar": "انعام‌دار",
    "enamorato": "عاشق‌وپیشه",
    "enanthem": "اگزانتم داخلی",
    "encaenia": "جشن تقدیس",
    "encanthis": "تومور گوشه چشم",
    "encarpus": "نقش‌ونگار میوه‌ای",
    "encell": "سلول‌بندی کردن",
    "Enchodontidae": "انخودونتیده",
    "enchytrae": "انکیتره",
    "enchytraeid": "کرم انکیترئید",
    "Enchytraeidae": "انکیترئیده",
    "Enchytraeus": "انکیترئوس",
    "encina": "بلوط سبز",
    "encinillo": "انسینیلو",
    "encoignure": "میز گوشه‌ای",
    "encolden": "سرد کردن",
    "encomendero": "انکمندروس",
    "encomienda": "انکمیندا",
    "encomium": "ستایش‌نامه",
    "encoronet": "تاج‌گذاری کردن",
    "encrinic": "مربوط به سوسن دریایی",
    "Encrinidae": "سوسن‌های دریایی (خانواده)",
    "encrinidae": "سوسن‌های دریایی",
    "Encrinoidea": "سوسن‌واران دریایی",
    "Encrinus": "انکرینوس",
    "encyrtid": "زنبور انسیرتید",
    "Encyrtidae": "انسیرتیده",
    "encyst": "کیست‌دار شدن",
    "encystation": "تشکیل کیست",
    "endamask": "داماسک کردن",
    "endameba": "آمیب روده‌ای",
    "endamebic": "مربوط به آمیب روده‌ای",
    "endaspidean": "انداسپیدین",
    "endenizen": "تبعه کردن",
    "endere": "اندره",
    "Endoceratidae": "اندوسراتیده",
    "endocyemate": "اندوسییمات",
    "endodynamorphic": "اندودینامورفیک",
    "endognath": "آرواره داخلی",
    "endothecate": "اندوتکات",
    "endungeon": "به زندان انداختن",
    "energumen": "جن‌زده",
    "energumenon": "انرگومنن",
    "enfatico": "با تاکید (در موسیقی)",
    "engaud": "شادی کردن",
    "engem": "گوهرنشین کردن",
    "engild": "زراندود کردن",
    "engjateigur": "انگیاتگر",
    "engladden": "شاد کردن",
    "engnessang": "انگ‌نسانگ",
    "engolden": "طلایی کردن",
    "Engraulidae": "شگ‌ماهیان (موتوماهیان)",
    "Engystomatidae": "دهان‌تنگان",
    "enhat": "کلاه سر گذاشتن",
    "enhelm": "کلاه‌خود گذاشتن",
    "Enhydrinae": "شنگ‌های دریایی",
    "Enicuridae": "انیکوریده",
    "enlink": "پیوند دادن",
    "enneadianome": "انئادیانوم",
    "enneagon": "نه‌ضلعی",
    "enneastyle": "نه‌ستونی",
    "enneastylos": "بنای نه‌ستونی",
    "enomania": "اعتیاد به شراب",
    "enoplan": "انوپلان",
    "enrib": "دنده کردن",
    "ens": "موجود",
    "ensand": "ماسه کردن",
    "ensandal": "صندل پوشاندن",
    "ense": "باشنده",
    "enseem": "به نظر رسیدن",
    "enserf": "به بردگی کشیدن",
    "ensete": "انست (موز حبشی)",
    "enshell": "پوسته‌دار کردن",
    "Ensiferi": "شمشیردُم‌ها",
    "ensisternum": "زائده خنجری سینه",
    "ensky": "به آسمان بردن",
    "ensorcell": "طلسم کردن",
    "ensphere": "در کره قرار دادن",
    "enteropneust": "کرم بلوطی",
    "Enteropneusta": "کرم‌های بلوطی (رده)",
    "entia": "موجودات",
    "entocuniform": "استخوان میخی داخلی",
    "Entomophthoraceae": "حشره‌خواران (قارچ)",
    "entrepas": "گام میانی اسب",
    "entrepot": "انبار کالا",
    "envermeil": "سرخ کردن",
    "enwisen": "دانا کردن",
    "eoan": "سپیده‌دمی",
    "Eoghanacht": "اوگاناکت",
    "Eomecon": "خوش‌خواب",
    "eosate": "ائوسات",
    "eoside": "ائوسید",
    "eozoon": "ائوزون",
    "epacmaic": "اپاکمیک",
    "epacme": "اوج تکامل",
    "epacrid": "اپاکرید",
    "Epacridaceae": "اپاکریداسته",
    "epacridaceous": "اپاکریداسته-مانند",
    "Epacris": "اپاکریس",
    "epagoge": "استقرا",
    "epagomenae": "روزهای پنجه (اضافه)",
    "epagomena": "روز پنجه",
    "epagomenic": "مربوط به روزهای پنجه",
    "epagomenous": "مربوط به روز پنجه",
    "epanadiplosis": "تکرار در ابتدا و انتها",
    "epanaphora": "تکرار کلمه در آغاز",
    "epanodos": "تکرار معکوس",
    "Epanorthidae": "اپانورتیده",
    "epanthous": "روی گل روینده",
    "eparcuale": "اپارکوال",
    "epauliere": "شانه‌پوش",
    "epee": "اپه (شمشیربازی)",
    "epeeist": "اپه‌باز",
    "Epeiridae": "عنکبوت‌های گردباف",
    "ependyme": "اپندیم",
    "ependytes": "لباس بیرونی",
    "epenthesis": "درمیان‌نهش (افزودن واج در میان واژه)",
    "epenthesize": "واج میان‌نهی کردن",
    "epepophysis": "اپپوفیز",
    "epergne": "ظرف تزئینی وسط میز",
    "epha": "ایفا (واحد وزن عبری)",
    "Ephemeridae": "یک‌روزه‌ها (خانواده حشره)",
    "Ephydridae": "مگس‌های ساحل",
    "epicaridan": "اپیکاریدان",
    "Epicaridea": "اپیکاریده",
    "Epicauta": "تاول‌سوسک‌ها",
    "epicentrum": "مرکز سطحی زلزله",
    "epicheirema": "قیاس چندگانه",
    "epicoelar": "اپیکولار",
    "epicentrum": "اپیسنتروم",
    "epicoelar": "اپیکولار",
    "epicondylar": "فوق لقمه‌ای",
    "epicoracohumeral": "اپیکوراکوهومرال",
    "Epicrates": "اپیکراتس",
    "epicrisis": "نتیجه‌گیری نهایی پزشکی",
    "epicycle": "فلک تدویر",
    "Epigaea": "اپیکیا",
    "epigenesist": "باورمند به اپی‌ژنز",
    "epiglottidean": "مربوط به برچاک‌نای",
    "epigonation": "زانونما (در لباس مذهبی)",
    "Epigonichthyidae": "اپیکونیکتیده",
    "Epigonichthys": "اپیکونیکتیس",
    "epigonos": "اخلاف",
    "epigrammatize": "به صورت کلمات قصار بیان کردن",
    "epigynum": "اپی‌گینوم",
    "epilimnion": "لایه فوقانی آب",
    "Epilobiaceae": "علف‌خریانیان",
    "Epimachinae": "مرغان بهشت (زیرخانواده)",
    "epimanikia": "ساق‌بند مذهبی",
    "epimorphic": "اپیمورفیک",
    "epimorphosis": "اپیمورفوز",
    "Epinephelidae": "هامورماهیان",
    "epinicion": "سرود پیروزی",
    "epiopticon": "اپتی‌کن",
    "epipastic": "گرد زخم",
    "epiphora": "ریزش اشک",
    "epiploce": "اپپلوک",
    "epiplocele": "فتق چادرینه",
    "epiploic": "مربوط به چادرینه",
    "epiploon": "چادرینه",
    "epipodiale": "اپپودیال",
    "epipubis": "اپپوبیس",
    "epirotulian": "اپیروتولیان",
    "episcenium": "بالای صحنه",
    "episclera": "اپی‌اسکلرا",
    "episkotister": "اپیسکوتیستر",
    "epispadiac": "مربوط به اپیسپادیاس",
    "epispastic": "تاول‌آور",
    "episternalia": "استخوان‌های بالای جناغ",
    "episternum": "اپی‌استرنوم",
    "epistilbite": "اپیس‌تیلبیت",
    "Epistylis": "اپیس‌تیلیس",
    "epitimesis": "توبیخ",
    "Epitoniidae": "صدف‌های نردبانی",
    "epitrite": "پای عروضی چهار هجایی",
    "epitrochlear": "فوق قرقره‌ای",
    "epivalve": "دریچه فوقانی",
    "eponymist": "نام‌گذار",
    "epoophoron": "اپوفورون",
    "epos": "حماسه",
    "Eproboscidea": "ایپروبوسیده",
    "Eptatretidae": "مکنده ماهیان",
    "epulis": "اپولیس (تومور لثه)",
    "epulo": "اپولو",
    "epuloid": "اپولوئید",
    "epulosis": "جوش خوردن زخم",
    "equinia": "مشمشه",
    "equinovarus": "پاچنبری",
    "equipaga": "خدمه کشتی",
    "Equisetaceae": "دم‌اسبیان",
    "Equisetales": "دم‌اسب‌سانان",
    "equispaced": "با فواصل مساوی",
    "equisurface": "هم‌سطح",
    "equuleus": "پاره‌اسب (صورت فلکی)",
    "Equus": "اسب (سرده)",
    "er": "حرف ار",
    "erectopatent": "نیمه افراشته",
    "Eremochaeta": "ارموکتا",
    "erenow": "پیش از این",
    "Erethizon": "تشی آمریکایی",
    "Erethizontidae": "تشی‌های جهان جدید",
    "erewhiles": "چندی پیش",
    "erg": "ارگ (واحد کار)",
    "ergonovine": "ارگونوین",
    "eria": "اریا",
    "Ericaceae": "خلنگیان",
    "erichthus": "اریکتوس",
    "Erinaceidae": "خارپشتان",
    "Erinize": "ایرلندی کردن",
    "Eriocaulaceae": "علف‌تابیان",
    "Eriophyidae": "کنه گالی",
    "erizo": "اریکو",
    "eroteme": "نشانه سوال",
    "Erpetoichthys": "طناب‌ماهی",
    "ers": "سنگنک",
    "ersatz": "جایگزین (نامرغوب)",
    "Ertebolle": "ارتبوله",
    "erubescite": "اروبسیت (بورنیت)",
    "eruc": "کرم حشره",
    "eruca": "منداب",
    "erysipelatoid": "شبیه سرخ‌باد",
    "erysipelatous": "مربوط به سرخ‌باد",
    "erysipelous": "سرخ‌بادی",
    "Erysiphaceae": "سفیدک‌های پودری",
    "Erythrinidae": "تتراهای گرگی",
    "Erythroxylaceae": "کوکائیان",
    "es": "حرف اس",
    "escarbuncle": "لعل",
    "escargatoire": "محل پرورش حلزون",
    "esconson": "اسکون‌سن",
    "escropulo": "اسکروپولو",
    "esne": "خدمتکار",
    "esoanhydride": "ازوآنهیدرید",
    "esocataphoria": "ازوکاتافوریا",
    "Esocidae": "اردک‌ماهیان",
    "esocyclic": "درون‌حلقه‌ای",
    "esonarthex": "نارتکس داخلی",
    "espalier": "داربست درخت",
    "esplees": "محصولات زمین",
    "esquirearchy": "حکومت اشراف‌زادگان",
    "ess": "حرف اس",
    "essang": "اسنگ",
    "essed": "ارابه جنگی دوچرخ",
    "Essenis": "اسنی",
    "Essenize": "اسنی کردن",
    "Estheriidae": "استرییده",
    "estmark": "واحد پول استونی",
    "estoc": "استوک (نوعی شمشیر)",
    "eta": "اتا (حرف یونانی)",
    "Etheostomidae": "دارترماهیان (خانواده قدیمی)",
    "Etheostominae": "دارترماهیان (زیرخانواده)",
    "Etheriidae": "صدف‌های آب شیرین",
    "ethmopalatal": "پرویزنی-کامی",
    "ethmoturbinal": "پرویزنی-شاخکی",
    "ethmoturbinate": "استخوان پرویزنی شاخکی",
    "ethmovomer": "پرویزنی-تیغه‌ای",
    "Etnean": "مربوط به کوه اتنا",
    "ettle": "قصد داشتن",
    "etui": "کیف لوازم کوچک",
    "etym": "ریشه واژه",
    "Eubasidii": "یوبازیدی‌ها",
    "eucairite": "اوکاریت",
    "Eucharitidae": "زنبورهای اوخاریتید",
    "Euchite": "اوخیت (فرقه مذهبی)",
    "Euchlorophyceae": "اوکلروفیسه",
    "euchroite": "اوکروئیت",
    "euchromatic": "خوش‌رنگ",
    "euchrome": "اوکروم",
    "euchrone": "اوکرون",
    "Eucleidae": "پروانه‌های حلزونی",
    "Eucnemidae": "سوسک‌های دروغین جهنده",
    "Eucommia": "اوکومیا",
    "Eucommiaceae": "اوکومیاسه",
    "euconic": "اوکنیک",
    "Euconjugatae": "اوکونژوگاته",
    "Eucopepoda": "پاروپایان حقیقی",
    "Eucosmidae": "اوکوسمیده",
    "eucrite": "اوکریت (نوعی شهاب‌سنگ)",
    "Eucryphiaceae": "اوکریفیاسه",
    "eucryphiaceous": "مربوط به اوکریفیاسه",
    "eucryptite": "اوکریپتیت",
    "eucyclic": "او سیکلیک",
    "eudaemon": "روح نیک",
    "eudaemonia": "سعادت",
    "eudaemonic": "سعادت‌بخش",
    "eudaemonical": "مربوط به سعادت",
    "eudaemonics": "اخلاق سعادت‌گرایانه",
    "eudaemonist": "سعادت‌گرا",
    "eudaemonize": "سعادت‌مند کردن",
    "eudaemony": "سعادت",
    "eudaimonia": "خوشبختی",
    "Eudyptes": "پنگوئن‌های کاکل‌دار",
    "Euergetes": "خیرخواه",
    "euge": "آفرین",
    "Euglenaceae": "اوگلناسه",
    "Euglenidae": "اوگلنیده",
    "Euglenineae": "اوگلنیان",
    "euhemerize": "تفسیر اسطوره‌ها به وقایع تاریخی",
    "euhyostylic": "اوهیوستیلیک",
    "euhyostyly": "اوهیوستیلی",
    "eulachon": "ماهی شمع",
    "eulalia": "اولالیا (نوعی علف)",
    "eulamellibranch": "تیغه‌آبشش‌دار حقیقی",
    "Eulamellibranchia": "تیغه‌آبششان حقیقی (رده)",
    "Eulamellibranchiata": "تیغه‌آبششان حقیقی",
    "Eulimidae": "حلزون‌های اولیمید",
    "eulytite": "اولیتایت",
    "Eumenidae": "زنبورهای سفالگر",
    "eumerism": "تقسیم متقارن بدن",
    "eumerogenesis": "تولید بخش‌های مشابه",
    "eumeromorph": "اومرومورف",
    "eumeromorphic": "اومرومورفیک",
    "eumitotic": "میتوز حقیقی",
    "Eumolpides": "اومولپیدها",
    "Eumolpus": "اومولپوس",
    "eumycete": "قارچ حقیقی",
    "Eunicidae": "یونیسیده",
    "euomphalid": "یومفالید",
    "euonymin": "یونیمین",
    "Euonymus": "توت‌کاس (سرده)",
    "Euornithes": "پرندگان حقیقی",
    "Euorthoptera": "راست‌بالان حقیقی",
    "euouae": "یوآئه (اصطلاح موسیقی مذهبی)",
    "eupad": "یوپاد",
    "Eupanorthidae": "یوپانورتیده",
    "Eupatorium": "غافث علفی",
    "eupatrid": "نجیب‌زاده (در آتن باستان)",
    "eupatridae": "نجیب‌زادگان آتنی",
    "Euphausiacea": "کریل‌ها (راسته)",
    "euphausiid": "کریل (موجود)",
    "Euphausiidae": "کریل‌ها (خانواده)",
    "Euphorbiaceae": "فرفیونیان",
    "Euphyllopoda": "برگ‌پایان حقیقی",
    "eupione": "یوپیون",
    "Euplectella": "سبد گل ونوس",
    "Euplexoptera": "گوش‌خیزک‌سانان",
    "Euplocomi": "یوپلوکومی",
    "Euploeinae": "یوپلوئینه",
    "eupnea": "تنفّس عادی",
    "Eupomatia": "یوپوماتia",
    "Eupomatiaceae": "یوپوماتiaسه",
    "eupractic": "خوش‌کردار",
    "Euproctis": "دم‌قهوه‌ای‌ها",
    "Euptelea": "یوپتلیا",
    "Eupterotidae": "یوپتروتیده",
    "eupyrion": "کبریت‌های اولیه",
    "eurite": "یوریت",
    "Euryaleae": "یوریاله",
    "eurybathic": "پهن‌ژرفا (در زیست‌شناسی)",
    "eurybenthic": "پهن‌کف‌زی",
    "Eurycerotidae": "یوری‌سروتیده",
    "Eurygaea": "یوری‌گاا",
    "Eurygaean": "مربوط به یوری‌گاا",
    "Eurylaimidae": "پهن‌نوکان",
    "Eurypharyngidae": "پلیکان‌مارماهیان",
    "Eurypharynx": "دهان‌گشاد (سرده مارماهی)",
    "Eurypterida": "عقرب‌های دریایی (راسته منقرض شده)",
    "Eurypteroidea": "عقرب‌واران دریایی",
    "Eurypyga": "حواصیل آفتابی",
    "Eurypygae": "حواصیل‌های آفتابی (گروه)",
    "Eurypygidae": "حواصیل‌های آفتابی (خانواده)",
    "Eurytomidae": "زنبورهای دانه‌خوار",
    "eusol": "یوسول (محلول ضدعفونی)",
    "eusporangiate": "هاگدان‌دار حقیقی",
    "eustyle": "میان‌ستون (در معماری)",
    "evangeliarium": "کتاب اناجیل",
    "evangelistarion": "بخش‌های انجیل (برای قرائت)",
    "evangelistarium": "کتاب قرائت انجیل",
    "Evaniidae": "زنبورهای پرچمی",
    "evansite": "اوانزیت",
    "evechurr": "بلدرچین‌خوان",
    "evejar": "شب‌گرد (پرنده)",
    "evelight": "نور شامگاهی",
    "eveque": "اسقف (فرانسوی)",
    "evertor": "برگرداننده (عضله)",
    "everwho": "هر کس که",
    "evoe": "فریاد شادی (در یونان باستان)",
    "evovae": "اووآئه (تغییر یافته euouae)",
    "evzone": "سرباز گارد یونانی",
    "ewelease": "چرای میش",
    "exactor": "گیرنده (به زور)",
    "exadversum": "روبرو",
    "exairesis": "خارج کردن اندام",
    "exallotriote": "بیگانه",
    "Exaudi": "اکسائودی (یکشنبه پیش از پنطیکاست)",
    "excamb": "مبادله کردن (زمین)",
    "excamber": "مبادله‌گر",
    "excambion": "مبادله زمین",
    "Excipulaceae": "اکسیپولاسه",
    "excipuliform": "اکسیپول‌شکل",
    "excipulum": "اکسیپولوم (در قارچ‌شناسی)",
    "exdelicto": "ناشی از جرم",
    "executrix": "وصی (زن)",
    "exedra": "نیمکت سنگی (در معماری)",
    "exencephalus": "برون‌مغز (نقص مادرزادی)",
    "exequatur": "جواز کنسولی",
    "exequy": "مراسم تشییع جنازه",
    "exlex": "خارج از قانون",
    "exmeridian": "خارج از نصف‌النهار",
    "Exmoor": "اکسمور (منطقه‌ای در انگلیس)",
    "Exoascaceae": "اکزوآسکاسه",
    "Exobasidiaceae": "اکزوبازیدیاسه",
    "Exobasidiales": "اکزوبازیدیال‌ها",
    "exocline": "اکزوکلین",
    "exocoelom": "سلوم خارجی",
    "Exocoetidae": "پرنده‌ماهیان",
    "Exocyclica": "اکزوسیکلیکا",
    "Exogenae": "برون‌زادها",
    "exomis": "اگزمیس (لباس یونانی)",
    "exomphalos": "فتق ناف",
    "exordia": "مقدمه‌ها",
    "exordium": "دیباچه",
    "exorhason": "ردای کشیشی",
    "exotheca": "پوشش خارجی",
    "expenditrix": "خرج‌کننده (زن)",
    "exradio": "خارج از شعاع",
    "exradius": "شعاع خارجی",
    "exsanguine": "بی‌خون",
    "exsectile": "قابل بریدن",
    "exsequatur": "اجازه‌نامه (مشابه exequatur)",
    "exsiccatae": "گیاهان خشک شده",
    "extima": "خارجی‌ترین لایه",
    "extispex": "فال‌گیر (از روی امعا و احشا)",
    "exuviae": "پوسته‌های دور ریخته شده",
    "exzodiacal": "خارج از منطقه البروج",
    "eyot": "جزیره کوچک رودخانه‌ای",
    "eyrir": "واحد پول ایسلند (ایریر)",
    "f": "حرف اف",
    "Fabaceae": "باقلائیان",
    "Fabraea": "فابرا (سرده قارچ)",
    "Fabroniaceae": "فابرونیاسه (نوعی خزه)",
    "facetiae": "لطایف و مطایبات",
    "fackeltanz": "رقص مشعل",
    "Fagaceae": "راشیان",
    "fahlore": "فالور (نوعی کانه مسی)",
    "fainaiguer": "تقلب کردن",
    "faitour": "شیاد",
    "Falconidae": "شاهینان",
    "Falconinae": "شاهین‌ها (زیرخانواده)",
    "faldfee": "مالیات فلد",
    "fanfaronading": "لاف‌زنی کردن",
    "faniente": "بیکاری",
    "fanwort": "کابومبا",
    "fardelet": "بسته کوچک",
    "farleu": "مالیات فاریو",
    "farnesol": "فارنسول",
    "farrago": "مجموعه درهم و برهم",
    "farrisite": "فاریسیت",
    "fasciculus": "بندیک (در زیست‌شناسی)",
    "Fasciolariidae": "حلزون‌های دوک‌شکل",
    "Fasciolidae": "کرم‌های جگر",
    "fatsia": "آرالیای ژاپنی",
    "faussebrayed": "دارای حصار محافظ",
    "faveolus": "حفره کوچک",
    "Favositidae": "فاووزیتیده",
    "faze": "آشفته کردن",
    "fazenda": "مزرعه بزرگ (در برزیل)",
    "fe": "حرف اف‌ای",
    "feering": "خط‌کشی شخم",
    "Felidae": "گربه‌سانان",
    "femerell": "دریچه خروج دود",
    "Fenestellidae": "فنستلیده",
    "fenestrato": "دارای پنجره (سوراخ)",
    "Ferae": "پستانداران گوشت‌خوار",
    "ferngale": "سرخس‌باد",
    "ferntickled": "کک‌ومکی",
    "ferthumlungur": "واحد طول قدیمی ایسلندی",
    "fetlow": "عفونت سم",
    "fetor": "بوی بد",
    "feuille": "برگ (فرانسوی)",
    "fiatconfirmatio": "اجازه تایید",
    "Ficoidaceae": "فیکوئیداسه",
    "Ficoideae": "فیکوئیده",
    "fideicommiss": "تراست یا امانت (حقوقی)",
    "fideicommissioner": "متولی تراست",
    "fideicommissor": "واگذارنده تراست",
    "fideicommissum": "تراست وصیتی",
    "fidejussion": "ضمانت",
    "fidejussor": "ضامن",
    "fidepromission": "تعهد کلامی",
    "Fides": "فیدس (الهه وفاداری)",
    "fidicinales": "عضلات انگشت‌نواز",
    "fiducia": "اعتماد (حقوقی)",
    "fiducinales": "عضلات فیدوسینال",
    "Fierasferidae": "ماهیان مروارید",
    "fifo": "خروج به ترتیب ورود (سیستم انبارداری)",
    "Figitidae": "زنبورهای فیگیتید",
    "figurante": "سیاهی‌لشکر (زن در اپرا)",
    "filariid": "کرم فیلاریایی",
    "Filariidae": "فیلارییده",
    "Filicales": "سرخس‌سانان",
    "Filices": "سرخس‌ها (رده)",
    "Filicineae": "سرخس‌تباران",
    "Filicites": "سرخس‌های فسیلی",
    "filioque": "فیلیوکه (اصطلاح الهیاتی)",
    "filite": "فیلایت (نوعی باروت)",
    "filleul": "فرزندخوانده (پسر در فرانسه)",
    "fillock": "مادیان جوان",
    "fillowite": "فیلوییت",
    "filmet": "فیلم کوتاه",
    "fils": "فرزند (فرانسوی)",
    "findjan": "فنجان",
    "Finiglacial": "فینی‌گلاسیال",
    "finjan": "فنجان",
    "finnac": "نوعی ماهی آزاد",
    "fiorded": "دارای آبدره",
    "Fissidentaceae": "فیسیدنتاسه (نوعی خزه)",
    "fissirostrate": "شکاف‌منقار",
    "Fissurellidae": "حلزون‌های کلاهی سوراخ‌دار",
    "Fistulariidae": "شیپورماهیان",
    "fjeld": "فلات مرتفع سنگی",
    "fjerding": "یک‌چهارم (واحد نروژی)",
    "Flacourtiaceae": "فلارکوراسه",
    "Flagellariaceae": "فلاژلاریاسه",
    "flapdoodle": "حرف پوچ",
    "flecnodal": "نقطه گره‌ای منحنی",
    "Fletcherize": "خوب جویدن غذا",
    "flibbertigibbet": "آدم وراج",
    "florilegium": "جُنگ ادبی",
    "Flosculariidae": "فلوسکولاریده",
    "flowoff": "جریان خروجی",
    "flubdub": "لاف و گزاف",
    "fluework": "لوله‌های صوتی ارگ",
    "flunkeydom": "چاپلوسی",
    "flustrum": "فلوستروم",
    "fluxroot": "ریشه اسهال‌بند",
    "flyblow": "تخم مگس",
    "Foeniculum": "رازیانه (سرده)",
    "folgerite": "فولگریت",
    "folkmote": "انجمن مردمی (در قدیم)",
    "Fontinalaceae": "فونتینالاسه (خزه آبی)",
    "Foochowese": "مردم یا زبان فوچو",
    "foralite": "فورالیت",
    "forane": "خارجی",
    "foraneen": "فورانین",
    "forb": "علف پهن‌برگ",
    "forbar": "ممانعت کردن",
    "forche": "فورشه (در شکار)",
    "Forcipulata": "چنگک‌داران (ستاره دریایی)",
    "Fordicidia": "فوردی‌سیدیا (جشن رومی)",
    "fordo": "نابود کردن",
    "forebay": "حوضچه آرامش",
    "foreorlop": "عرشه زیرین جلویی",
    "forfars": "پارچه کتانی زبر",
    "Forficulidae": "گوش‌خیزک‌ها (خانواده)",
    "forfouchten": "خسته و فرسوده",
    "forhoo": "ترک کردن",
    "forinsec": "خارجی (در قدیم)",
    "forjesket": "خسته",
    "Formicariae": "مورچه‌گیران",
    "Formicariidae": "مورچه‌مرغان",
    "Formicidae": "مورچگان",
    "Formicinae": "مورچه‌ها (زیرخانواده)",
    "Formicivora": "مورچه‌خواران (سرده پرنده)",
    "Formicoidea": "مورچه‌واران",
    "fornenst": "در مقابل",
    "forninst": "روبرو",
    "forpine": "از غصه آب شدن",
    "forpit": "یک‌چهارم پیمانه",
    "forprise": "استثنا کردن (حقوقی)",
    "forrad": "به جلو",
    "forrit": "جلو",
    "forthfare": "عزیمت",
    "forthgaze": "خیره شدن به جلو",
    "Fouquieriaceae": "فوکیوریاسه",
    "foveate": "دارای چاله",
    "foveole": "گودی کوچک",
    "foveolet": "چاله بسیار کوچک",
    "fra": "برادر (مذهبی)",
    "frache": "فراشه",
    "frae": "از (لهجه اسکاتلندی)",
    "Fragilariaceae": "فراگیلاریاسه",
    "frailejon": "فرایلخون (گیاه)",
    "fraise": "حصار نوک‌تیز",
    "frampler": "آدم ستیزه‌جو",
    "frampold": "بدخلق",
    "Frangulaceae": "سیاه‌تلیان (نام قدیمی)",
    "frase": "حصاربندی کردن",
    "frasier": "توت‌فرنگی (در نشان‌های خانوادگی)",
    "frasier": "توت‌فرنگی",
    "frass": "فضولات حشرات",
    "frayn": "پرسیدن",
    "Fregatidae": "مرغان فرگات",
    "freir": "کشیش",
    "Freycinetia": "فریسنتیا",
    "friarbird": "پرنده راهب",
    "fricatrice": "زن بدکاره",
    "fridstool": "صندلی پناهگاه",
    "frijolillo": "لوبیاچه",
    "Fringillidae": "سهره‌ئیان",
    "Frisesomorum": "فریسهوموروم",
    "frisure": "آرایش مو",
    "frithbot": "جریمه شکستن صلح",
    "frithsoken": "حق پناهندگی",
    "frognose": "بینی قورباغه‌ای",
    "frontad": "به سمت جلو",
    "Fucaceae": "فوکاسه (جلبک قهوه‌ای)",
    "fucate": "آرایش شده",
    "Fucoideae": "فوکوئیده",
    "fuerte": "فورت (تند)",
    "fulgide": "فولگاید",
    "Fulgoridae": "زنجره‌های فانوسی",
    "Fulgoroidea": "زنجره‌واران",
    "Fulicinae": "چنگرها (زیرخانواده)",
    "Fumariaceae": "شاه‌ترگان",
    "fumeroot": "شاه‌تره",
    "Funariaceae": "فوناریاسه (نوعی خزه)",
    "Fundulinae": "ماهیان مومی (زیرخانواده)",
    "fundungi": "ارزن آفریقایی",
    "funis": "بند ناف",
    "funori": "فانوری (نوعی چسب جلبکی)",
    "Furcellaria": "فورس‌لاریا",
    "Furcraea": "فورکرا",
    "furdel": "بسته",
    "furiosa": "خشمگینانه (در موسیقی)",
    "Furnariidae": "پرندگان تنورمرغ",
    "Furnariides": "تنورمرغان (گروه)",
    "Furnarius": "تنورمرغ (سرده)",
    "furuncle": "دمبل",
    "furzechat": "چک‌چک (پرنده)",
    "furzetop": "بوته خلنگ",
    "fusc": "تیره رنگ",
    "fusoid": "دوک‌مانند",
    "fusser": "آدم وسواسی",
    "futhorc": "الفبای رونی",
    "fuye": "فرار",
    "fuzz": "کرک",
    "fyke": "تور ماهیگیری کیسه‌ای",
    "g": "حرف جی",
    "ga": "حرف گا",
    "gadabout": "ولگرد",
    "Gadidae": "ماهیان خاویاری (کاد)",
    "Gadoidea": "کادواران",
    "Gaeltacht": "مناطق ایرلندی‌زبان",
    "gaen": "رفته",
    "Gaidropsaridae": "گایدروساریده",
    "gaincall": "فراخوان",
    "Galacaceae": "گالاکاسه",
    "galactophlysis": "تاول شیری",
    "galactophore": "مجرای شیر",
    "galactophthysis": "سل پستان",
    "Galaginae": "گالاگوها (زیرخانواده)",
    "Galaxiidae": "کهکشان‌ماهیان",
    "Galbulae": "گالبولائه",
    "Galbulidae": "یشم‌مرغان",
    "Galbulinae": "یشم‌مرغان (زیرخانواده)",
    "Galeidae": "گوش‌ماهی‌های ببری (کوسه)",
    "Galeodidae": "عنکبوت‌های شتری",
    "Galeorhinidae": "گالیورینیده",
    "galera": "گالرا",
    "Galgulidae": "قورباغه‌سوسک‌ها",
    "galimatias": "حرف‌های نامفهوم",
    "Galleriidae": "شب‌پره‌های موم‌خوار",
    "Gallinaceae": "ماکیان‌سانان (قدیمی)",
    "Gallinulinae": "چنگرها",
    "galziekte": "بیماری کیسه صفرا (در دام)",
    "Gamasidae": "کنه های گاماسید",
    "Gamasoidea": "گاماسوئیده",
    "gamboised": "پوشیده شده با لایه محافظ",
    "gamdeboo": "گامدبو",
    "Gammaridae": "گاماریده (میگوهای آب شیرین)",
    "gammelost": "پنیر قدیمی نروژی",
    "Gamopetalae": "پیوسته‌گلبرگان",
    "gamopetalous": "پیوسته‌گلبرگ",
    "gantsl": "دستکش",
    "gaolbird": "زندانی سابقه دار",
    "Gaonate": "دوره گائونیم",
    "gapingstock": "مایه تمسخر",
    "garewaite": "گارویت",
    "Garryaceae": "گاریاسه",
    "gascromh": "گاسکروم (نوعی خیش دستی)",
    "Gasterosteidae": "ماهیان خاردل",
    "Gastornithidae": "گاستورنیتیده",
    "Gastraeadae": "گاسترائده",
    "Gastrochaena": "گاستروکنا",
    "Gastrochaenidae": "گاستروکنیده",
    "gat": "گذرگاه آبی",
    "gavelkind": "تقسیم ارث مساوی (در قدیم)",
    "Gaviae": "غواص‌سانان (قدیمی)",
    "Gaviiformes": "غواص‌سانان",
    "gawkhammer": "آدم احمق",
    "gaylussite": "گیلوسیت",
    "gazettal": "اعلام در روزنامه رسمی",
    "gazingstock": "مایه عبرت یا تمسخر",
    "Geadephaga": "گادفاگا (سوسک‌های زمینی)",
    "gebang": "نخل گبانگ",
    "Gecarcinidae": "خرچنگ‌های زمینی",
    "Geckotidae": "گکوها (خانواده)",
    "ged": "اردک‌ماهی (اسکاتلندی)",
    "gedackt": "گدکت (در ارگ)",
    "gedeckt": "گدکت (پوشیده)",
    "gedecktwork": "صدای گدکت",
    "geebung": "گی‌بانگ (گیاه)",
    "geepound": "واحد جرم (اسلاگ)",
    "geest": "خاک پست",
    "geggery": "فریب",
    "Geheimrat": "مشاور عالی (آلمانی)",
    "geikielite": "گیکلیت",
    "gein": "گین",
    "Geissolomataceae": "گیسولوماتاسه",
    "gekkonid": "گکو",
    "Gekkonidae": "گکوها",
    "gekkonoid": "گکومورف",
    "Gelastocoridae": "سوسک‌های وزغی",
    "gelechiid": "شب‌پره‌های گلشید",
    "Gelechiidae": "گلشیدیان",
    "Gelidiaceae": "گلیدیاسه (جلبک قرمز)",
    "gematria": "جماتریا (حروف ابجد یهودی)",
    "gemmipara": "جوانه‌زاها",
    "gemmipares": "جوانه‌زایان",
    "gemot": "انجمن",
    "gemsbok": "غزال بزرگ آفریقایی",
    "gemuti": "جموتی",
    "genapp": "جناپ (نوعی نخ)",
    "Genesee": "جنسی (نام مکان)",
    "Genesiac": "مربوط به سفر پیدایش",
    "genethliacon": "شعر تولد",
    "genetmoil": "نوعی سیب",
    "Genevese": "اهل ژنو",
    "Genevieve": "ژنویو",
    "genevoise": "ژنوی",
    "genioglossal": "چانه‌ای-زبانی",
    "genioglossi": "عضلات چانه‌ای-زبانی",
    "genioglossus": "عضله چانه‌ای-زبانی",
    "geniohyoglossal": "چانه‌ای-لامی-زبانی",
    "geniohyoglossus": "عضله چانه‌ای-لامی-زبانی",
    "genipap": "جنیپاپ (میوه)",
    "genipapada": "جنیپاپادا",
    "genizero": "جنیزرو",
    "genovino": "سکه جنوا",
    "Gentianaceae": "جنتیانیان (گل سپاس)",
    "gentianwort": "گل سپاس",
    "gentisein": "جنتیسین",
    "genyantrum": "حفره فک بالا",
    "Genyophrynidae": "ژنیوفریتیده",
    "geobiont": "زمین‌زی",
    "geobios": "حیات زمینی",
    "Geoglossaceae": "قارچ‌های زبان‌زمین",
    "geognosis": "زمین‌شناسی توصیفی",
    "geognost": "زمین‌شناس توصیفی",
    "Geometridae": "زمین‌سنجان (کرم‌های اندازه‌گیر)",
    "Geometrina": "زمین‌سنج‌ها (گروه)",
    "Geometroidea": "زمین‌سنج‌واران",
    "Geomyidae": "موش‌های کیسه‌دار",
    "Geophilidae": "صدپاهای زمینی",
    "Geoplanidae": "کرم‌های پهن زمینی",
    "Geoteuthis": "ژئوتوتیس",
    "Gepeoo": "ژپئو",
    "Gephyrea": "ژفیره (کرم‌های دریایی)",
    "Gepidae": "ژپیدها (قوم ژرمن)",
    "Geraniaceae": "شمعدانیان",
    "Gerbillinae": "جربیل‌ها (زیرخانواده)",
    "gerefa": "مقام اداری (در قدیم)",
    "gerenuk": "غزال گردن‌دراز",
    "gerontes": "شورای پیران",
    "Gerrhosauridae": "مارمولک‌های زره‌پوش",
    "Gerridae": "آب‌سواران (حشره)",
    "gersdorffite": "گرسدورفیت",
    "gersum": "هزینه ورود (در قدیم)",
    "Geryonidae": "ژریونیده",
    "Geryoniidae": "ژریونیده (مدوز)",
    "Ges": "جی‌ئی‌اس",
    "gesithcund": "نجیب‌زاده",
    "gesithcundman": "نجیب‌زاده (در قدیم)",
    "Gesnera": "جس‌نرا",
    "Gesneraceae": "جس‌نراسه",
    "gesneria": "جس‌نریا",
    "Gesneriaceae": "جس‌نریاسه",
    "gesning": "مهمان‌نوازی",
    "gest": "کار نمایان",
    "gestant": "باردار",
    "gesten": "مهمان شدن",
    "gewgaw": "اسباب‌بازی بی‌ارزش",
    "gewgawish": "زرق و برق‌دار",
    "gewgawry": "اشیاء بی‌ارزش",
    "gez": "گاز (واحد طول)",
    "Gi": "جی‌آی",
    "Gib": "گیب",
    "gib": "گربه نر",
    "gibbsite": "گیبسیت",
    "gibus": "کلاه سیلندر تاشو",
    "gid": "بیماری چرخش در گوسفند",
    "giddea": "گیدا",
    "gien": "داده شده",
    "gieseckite": "گیزکیت",
    "gif": "گیف",
    "Gigantopithecus": "گیگانتوپیتکوس (کپی غول‌پیکر)",
    "Gigantosaurus": "گیگانتوسور (دایناسور غول‌پیکر)",
    "Gigantostraca": "گیگانتوستراکا",
    "gigantostracan": "غول‌پیکر سخت‌پوست",
    "Gigartinaceae": "گیگارتیناسه (جلبک قرمز)",
    "Gigartinales": "گیگارتینال‌ها",
    "gigeria": "سنگدان",
    "gigliato": "سکه جیگلیاتو",
    "gillstoup": "پیمانه دسته دار",
    "gillygaupus": "آدم نادان",
    "gimmerpet": "میش جوان",
    "ging": "دسته",
    "gingersnap": "شیرینی زنجبیلی",
    "ginghamed": "دارای پارچه پیچازی",
    "ginglyform": "لولامانند",
    "ginglymoarthrodia": "مفصل لولایی-لغزشی",
    "ginglymoarthrodial": "مربوط به مفصل لولایی-لغزشی",
    "ginglymodian": "لولایی‌مورف",
    "ginglymoid": "لولامانند",
    "ginglymoidal": "شبیه مفصل لولایی",
    "Ginglymostoma": "کوسه‌های پرستار (سرده)",
    "ginglymostomoid": "کوسه‌پرستاروار",
    "ginglymus": "مفصل لولایی",
    "ginglyni": "جینگ‌لینی",
    "Ginkgoaceae": "کهنیان",
    "gio": "جیو",
    "gipser": "گچ‌کار",
    "gipsire": "کیسه پول",
    "gipsyweed": "سیزاب",
    "girandole": "شمعدان چندشاخه",
}

def transliterate(word):
    mapping = {
        'ph': 'ف', 'ch': 'چ', 'sh': 'ش', 'th': 'ت', 'ae': 'آ', 'oe': 'و', 'aa': 'آ',
        'c': 'ک', 'k': 'ک', 'q': 'ک', 'x': 'کس', 'a': 'آ', 'b': 'ب', 'd': 'د',
        'e': 'ه', 'f': 'ف', 'g': 'گ', 'h': 'ه', 'i': 'ی', 'j': 'ج', 'l': 'ل',
        'm': 'م', 'n': 'ن', 'o': 'و', 'p': 'پ', 'r': 'ر', 's': 'س', 't': 'ت',
        'u': 'و', 'v': 'و', 'w': 'و', 'y': 'ی', 'z': 'ز'
    }
    word = word.lower()
    res = ""
    i = 0
    while i < len(word):
        if word[i:i+2] in ['ph', 'ch', 'sh', 'th', 'ae', 'oe', 'aa']:
            res += mapping[word[i:i+2]]
            i += 2
        elif word[i] == 'c':
            if i+1 < len(word) and word[i+1] in ['e', 'i', 'y']:
                res += 'س'
            else:
                res += 'ک'
            i += 1
        elif word[i] in mapping:
            res += mapping[word[i]]
            i += 1
        else:
            i += 1
    return res

def translate_word(word):
    if word in manual_fixes: return manual_fixes[word]
    if word.lower() in manual_fixes: return manual_fixes[word.lower()]
    
    # Taxonomic suffixes
    if word.endswith('aceae'): return transliterate(word[:-5]) + 'یان'
    if word.endswith('idae'): return transliterate(word[:-4]) + 'ان'
    if word.endswith('ales'): return transliterate(word[:-4]) + 'سانان'
    if word.endswith('inae'): return transliterate(word[:-4]) + 'اینه'
    if word.endswith('oidei'): return transliterate(word[:-5]) + 'ویدئی'
    if word.endswith('oidea'): return transliterate(word[:-5]) + 'واران'
    if word.endswith('iformes'): return transliterate(word[:-7]) + 'سانان'
    
    return transliterate(word)

def main():
    with open('en2.txt', 'r', encoding='utf-8') as f:
        words = [line.strip() for line in f if line.strip()]
    
    translated = {word: translate_word(word) for word in words}
    
    with open('en2_translated.json', 'w', encoding='utf-8') as f:
        json.dump(translated, f, ensure_ascii=False, indent=2)

if __name__ == "__main__":
    main()
