import json
import sys

# Since I am the model, I will define the translations here for the first chunk.
# In a real scenario, I might call myself to generate this.
# For this task, I will provide the translations as a dictionary.

chunk1_translations = {
    "Eatanswill": "ایتنزویل",
    "eatberry": "توت خوراکی",
    "Ebenaceae": "آبنوسیان",
    "Ebionitic": "ابیونی",
    "ebracteolate": "بی‌برگچه",
    "ebulus": "پلم",
    "eburine": "عاجی",
    "eburnean": "عاج‌مانند",
    "eburneoid": "عاج‌وار",
    "ecad": "اکاد (ریخت سازشی)",
    "ecanda": "اکاندا",
    "ecarinate": "بی‌تیغه",
    "ecarte": "اکارته (نوعی بازی ورق)",
    "Ecaudata": "بی‌دمان",
    "eccaleobion": "ماشین جوجه‌کشی",
    "eccyclema": "اکیکلمه (در تئاتر یونان)",
    "ecdemite": "اکدمیت",
    "ecdysiast": "پوست‌انداز (در اینجا رقاصه)",
    "ecdysis": "پوست‌اندازی",
    "echelette": "اشلت (توری پراش)",
    "Echeloot": "اچلوت",
    "Echeneidae": "چسب‌ماهیان",
    "echeneidid": "چسب‌ماهی‌سان",
    "Echeneididae": "خانواده چسب‌ماهیان",
    "Echeneis": "سرده چسب‌ماهی",
    "Echidnidae": "اکیدنیده (خارپشت‌خوراکان)",
    "Echimys": "موش‌های تیغ‌دار",
    "Echinoidea": "خارپوستان (توتیاهای دریایی)",
    "Echinorhinidae": "سگ‌ماهیان خشن",
    "Echinosphaeritidae": "اکینوسفریتیان",
    "Echinostomatidae": "اکینوستوماتیده",
    "echinuliform": "خاردارشکل",
    "Echites": "اشیتس",
    "echiurid": "کرم قاشقی",
    "Echiuroidea": "کرم‌های قاشقی‌شکل",
    "Echiurus": "اشیروس",
    "ecize": "سازگار شدن با محیط",
    "eclipsareon": "ابزار نمایش کسوف",
    "eclogite": "اکلوژیت",
    "ecphonesis": "ندا (در بیان)",
    "ectad": "به سمت خارج",
    "ectiris": "بخش خارجی عنبیه",
    "Ectocarpaceae": "اکتوکارپاسه",
    "ectocinerea": "قشر خاکستری خارجی مغز",
    "ectocuniform": "استخوان میخی خارجی",
    "ectoentad": "از خارج به داخل",
    "Ectoparasitica": "انگل‌های خارجی",
    "ectoretina": "لایه خارجی شبکیه",
    "Eddaic": "ادایی (مربوط به اداها)",
    "eddyroot": "ریشه گردابی",
    "edeagra": "درد اندام تناسلی",
    "Edenize": "عدن‌گونه کردن",
    "Edentata": "بی‌دندانان",
    "edestin": "ادستین (پروتئین گیاهی)",
    "edgeman": "تیغه‌دار",
    "edh": "حرف اد (ð)",
    "Edrioasteroidea": "ادروآستروئیدها",
    "educand": "آموزش‌گیرنده",
    "Edwardsiidae": "ادواردسیده",
    "eellike": "مارماهی‌شکل",
    "eelpout": "مارماهی‌نما",
    "eelshop": "مارماهی‌فروشی",
    "eely": "مارماهی‌وار",
    "efform": "شکل دادن",
    "effund": "ریختن",
    "efoliolate": "بی‌برگچه",
    "efoveolate": "بی‌گودی",
    "eft": "سمندر",
    "eftest": "سریع‌ترین",
    "eftsoons": "بزودی",
    "egence": "نیاز",
    "egest": "دفع کردن",
    "egesta": "مواد دفعی",
    "egger": "تخم‌گذار",
    "egilops": "علف پشمکی",
    "Eglamore": "اگلامور",
    "eglatere": "نسترن",
    "egol": "ایگول",
    "egrimony": "غافث",
    "egueiite": "اگوییت",
    "Ehatisaht": "اهاتیسات",
    "eheu": "آه و افسوس",
    "Ehretiaceae": "اهرتیاسه",
    "ehuawa": "اهواوا",
    "eichbergite": "آیش‌برگیت",
    "eigne": "فرزند ارشد",
    "Eireannach": "ایرلندی",
    "eiresione": "ایرسیون (در یونان باستان)",
    "eisegesis": "تفسیر به رأی",
    "eisteddfod": "ایستدفاد (جشنواره ولزی)",
    "eisteddfodic": "مربوط به ایستدفاد",
    "eisteddfodism": "نهضت ایستدفاد",
    "ejoo": "فیبر نخل",
    "eke": "افزودن",
    "eker": "اکر",
    "ekerite": "اکریت",
    "eking": "تکمیل",
    "ekphore": "احضار خاطره",
    "ektene": "دعای پی‌در‌پی",
    "ektenes": "دعاهای پی‌در‌پی",
    "ektodynamorphic": "اکتودینامورفیک",
    "el": "حرف ال",
    "Elachistaceae": "الاکیستاسه",
    "elaeoblast": "الائوبلاست",
    "Elaeocarpaceae": "الائوکاسپاسه",
    "elaeocarpaceous": "الائوکاسپاسه-مانند",
    "elaeodochon": "غده چربی",
    "elaeosaccharum": "روغن قند",
    "elaidinic": "الائیدینیک",
    "elaioplast": "الائوپلاست",
    "elanet": "کورکور سفید",
    "Elaphomycetaceae": "الافومیستاسه",
    "Elapidae": "کفچه‌ماران",
    "Elapinae": "کفچه‌مارها (زیرخانواده)",
    "Elapsoidea": "الاپسوئیدها",
    "elasmobranch": "غضروف‌ماهی",
    "elasmobranchiate": "دارای آبشش‌های تیغه‌ای",
    "Elasmobranchii": "تیغه‌آبششان",
    "elasmothere": "الاسموتریوم",
    "Elateridae": "سوسک‌های جهنده",
    "Elatinaceae": "لاتیناسه",
    "elcaja": "الکاجا",
    "eld": "پیری",
    "Electrophoridae": "مارماهیان الکتریکی",
    "eleemosynariness": "صدقه‌دهی",
    "eleemosynary": "خیریه",
    "elemi": "المی (نوعی صمغ)",
    "eleoblast": "الئوبلاست",
    "eleomargaric": "الئومارگاریک",
    "eleostearate": "الئواستئارات",
    "eleostearic": "الئواستئاریک",
    "Elephantidae": "فیلان",
    "eleutherodactyl": "پنجه‌آزاد",
    "Eleutherodactyli": "پنجه‌آزادان",
    "eleutheromania": "شیدایی آزادی",
    "eleutheromorph": "آزادمورف",
    "eleutheropetalous": "جداگلبرگ",
    "Eleutherozoa": "آزادزیان",
    "eleutherozoan": "مربوط به آزادزیان",
    "elevon": "الون (در هواپیما)",
    "elfenfolk": "جن و پریان",
    "ellachick": "لاک‌پشت جوان",
    "elle": "او (مؤنث در فرانسه)",
    "ellenyard": "ایل‌نیارد",
    "elod": "الود",
    "Elodeaceae": "الوداسه",
    "eloge": "ستایش‌نامه",
    "elogium": "کتیبه ستایش‌آمیز",
    "Elopidae": "ده‌باله‌ماهیان",
    "elotillo": "الوتیلو",
    "els": "الس",
    "elt": "خوک ماده جوان",
    "eluvium": "الویوم (رسوب درجا)",
    "Elysiidae": "الیسیده",
    "elytriform": "بالپوش‌شکل",
    "elytrigerous": "بالپوش‌دار",
    "elytroclasia": "شکستگی بالپوش",
    "elytropolypus": "پولیپ واژینال",
    "Em": "حرف ام",
    "emajagua": "اماجاگوا",
    "emanativ": "تراوشی",
    "emarcid": "پژمرده",
    "Emballonuridae": "خفاش‌های کیسه‌بال",
    "Embden": "آمدن",
    "emberizidae": "زردپرهیان",
    "Emberizinae": "زردپره‌ها (زیرخانواده)",
    "emberizine": "مربوط به زردپره",
    "Embiidae": "امبیده",
    "Embiotocidae": "زنده‌زا‌ماهیان",
    "Emerita": "امریتا",
    "Emesa": "حمص (نام تاریخی)",
    "Emesidae": "امسیده",
    "Emm": "حرف ام",
    "emodin": "امودین",
    "empanoply": "کاملاً مسلح کردن",
    "Empetraceae": "امپتراسه",
    "Empididae": "مگس‌های رقصنده",
    "emprosthotonos": "انقباض رو به جلو",
    "Empusa": "امپوسا",
    "emu": "امو (شترمرغ استرالیایی)",
    "emyd": "لاک‌پشت برکه‌ای",
    "Emydidae": "لاک‌پشت‌های برکه‌ای",
    "Emydinae": "لاک‌پشت‌های برکه‌ای (زیرخانواده)",
    "en": "حرف ان",
    "enaena": "انائنا",
    "enalid": "گیاه دریایی",
    "Enaliornis": "انالیورنیس",
    "enamdar": "انعام‌دار",
    "enamorato": "عاشق‌وپیشه",
    "enanthem": "اگزانتم داخلی",
    "encaenia": "جشن تقدیس",
    "encanthis": "تومور گوشه چشم",
    "encarpus": "نقش‌ونگار میوه‌ای",
    "encell": "سلول‌بندی کردن",
    "Enchodontidae": "انخودونتیده",
    "enchytrae": "انکیتره",
    "enchytraeid": "کرم انکیترئید",
    "Enchytraeidae": "انکیترئیده",
    "Enchytraeus": "انکیترئوس",
    "encina": "بلوط سبز",
    "encinillo": "انسینیلو",
    "encoignure": "میز گوشه‌ای",
    "encolden": "سرد کردن",
    "encomendero": "انکمندروس",
    "encomienda": "انکمیندا",
    "encomium": "ستایش‌نامه",
    "encoronet": "تاج‌گذاری کردن",
    "encrinic": "مربوط به سوسن دریایی",
    "Encrinidae": "سوسن‌های دریایی (خانواده)",
    "encrinidae": "سوسن‌های دریایی",
    "Encrinoidea": "سوسن‌واران دریایی",
    "Encrinus": "انکرینوس",
    "encyrtid": "زنبور انسیرتید",
    "Encyrtidae": "انسیرتیده",
    "encyst": "کیست‌دار شدن",
    "encystation": "تشکیل کیست",
    "endamask": "داماسک کردن",
    "endameba": "آمیب روده‌ای",
    "endamebic": "مربوط به آمیب روده‌ای",
    "endaspidean": "انداسپیدین",
    "endenizen": "تبعه کردن",
    "endere": "اندره",
    "Endoceratidae": "اندوسراتیده",
    "endocyemate": "اندوسییمات",
    "endodynamorphic": "اندودینامورفیک",
    "endognath": "آرواره داخلی",
    "endothecate": "اندوتکات",
    "endungeon": "به زندان انداختن",
    "energumen": "جن‌زده",
    "energumenon": "انرگومنن",
    "enfatico": "با تاکید (در موسیقی)",
    "engaud": "شادی کردن",
    "engem": "گوهرنشین کردن",
    "engild": "زراندود کردن",
    "engjateigur": "انگیاتگر",
    "engladden": "شاد کردن",
    "engnessang": "انگ‌نسانگ",
    "engolden": "طلایی کردن",
    "Engraulidae": "شگ‌ماهیان (موتوماهیان)",
    "Engystomatidae": "دهان‌تنگان",
    "enhat": "کلاه سر گذاشتن",
    "enhelm": "کلاه‌خود گذاشتن",
    "Enhydrinae": "شنگ‌های دریایی",
    "Enicuridae": "انیکوریده",
    "enlink": "پیوند دادن",
    "enneadianome": "انئادیانوم",
    "enneagon": "نه‌ضلعی",
    "enneastyle": "نه‌ستونی",
    "enneastylos": "بنای نه‌ستونی",
    "enomania": "اعتیاد به شراب",
    "enoplan": "انوپلان",
    "enrib": "دنده کردن",
    "ens": "موجود",
    "ensand": "ماسه کردن",
    "ensandal": "صندل پوشاندن",
    "ense": "باشنده",
    "enseem": "به نظر رسیدن",
    "enserf": "به بردگی کشیدن",
    "ensete": "انست (موز حبشی)",
    "enshell": "پوسته‌دار کردن",
    "Ensiferi": "شمشیردُم‌ها",
    "ensisternum": "زائده خنجری سینه",
    "ensky": "به آسمان بردن",
    "ensorcell": "طلسم کردن",
    "ensphere": "در کره قرار دادن",
    "enteropneust": "کرم بلوطی",
    "Enteropneusta": "کرم‌های بلوطی (رده)",
    "entia": "موجودات",
    "entocuniform": "استخوان میخی داخلی",
    "Entomophthoraceae": "حشره‌خواران (قارچ)",
    "entrepas": "گام میانی اسب",
    "entrepot": "انبار کالا",
    "envermeil": "سرخ کردن",
    "enwisen": "دانا کردن",
    "eoan": "سپیده‌دمی",
    "Eoghanacht": "اوگاناکت",
    "Eomecon": "خوش‌خواب",
    "eosate": "ائوسات",
    "eoside": "ائوسید",
    "eozoon": "ائوزون",
    "epacmaic": "اپاکمیک",
    "epacme": "اوج تکامل",
    "epacrid": "اپاکرید",
    "Epacridaceae": "اپاکریداسته",
    "epacridaceous": "اپاکریداسته-مانند",
    "Epacris": "اپاکریس",
    "epagoge": "استقرا",
    "epagomenae": "روزهای پنجه (اضافه)",
    "epagomena": "روز پنجه",
    "epagomenic": "مربوط به روزهای پنجه",
    "epagomenous": "مربوط به روز پنجه",
    "epanadiplosis": "تکرار در ابتدا و انتها",
    "epanaphora": "تکرار کلمه در آغاز",
    "epanodos": "تکرار معکوس",
    "Epanorthidae": "اپانورتیده",
    "epanthous": "روی گل روینده",
    "eparcuale": "اپارکوال",
    "epauliere": "شانه‌پوش",
    "epee": "اپه (شمشیربازی)",
    "epeeist": "اپه‌باز",
    "Epeiridae": "عنکبوت‌های گردباف",
    "ependyme": "اپندیم",
    "ependytes": "لباس بیرونی",
    "epenthesis": "درمیان‌نهش (افزودن واج در میان واژه)",
    "epenthesize": "واج میان‌نهی کردن",
    "epepophysis": "اپپوفیز",
    "epergne": "ظرف تزئینی وسط میز",
    "epha": "ایفا (واحد وزن عبری)",
    "Ephemeridae": "یک‌روزه‌ها (خانواده حشره)",
    "Ephydridae": "مگس‌های ساحل",
    "epicaridan": "اپیکاریدان",
    "Epicaridea": "اپیکاریده",
    "Epicauta": "تاول‌سوسک‌ها",
    "epicentrum": "مرکز سطحی زلزله",
    "epicheirema": "قیاس چندگانه",
    "epicoelar": "اپیکولار",
    "epicentrum": "اپیسنتروم",
    "epicoelar": "اپیکولار",
    "epicondylar": "فوق لقمه‌ای",
    "epicoracohumeral": "اپیکوراکوهومرال",
    "Epicrates": "اپیکراتس",
    "epicrisis": "نتیجه‌گیری نهایی پزشکی",
    "epicycle": "فلک تدویر",
    "Epigaea": "اپیکیا",
    "epigenesist": "باورمند به اپی‌ژنز",
    "epiglottidean": "مربوط به برچاک‌نای",
    "epigonation": "زانونما (در لباس مذهبی)",
    "Epigonichthyidae": "اپیکونیکتیده",
    "Epigonichthys": "اپیکونیکتیس",
    "epigonos": "اخلاف",
    "epigrammatize": "به صورت کلمات قصار بیان کردن",
    "epigynum": "اپی‌گینوم",
    "epilimnion": "لایه فوقانی آب",
    "Epilobiaceae": "علف‌خریانیان",
    "Epimachinae": "مرغان بهشت (زیرخانواده)",
    "epimanikia": "ساق‌بند مذهبی",
    "epimorphic": "اپیمورفیک",
    "epimorphosis": "اپیمورفوز",
    "Epinephelidae": "هامورماهیان",
    "epinicion": "سرود پیروزی",
    "epiopticon": "اپتی‌کن",
    "epipastic": "گرد زخم",
    "epiphora": "ریزش اشک",
    "epiploce": "اپپلوک",
    "epiplocele": "فتق چادرینه",
    "epiploic": "مربوط به چادرینه",
    "epiploon": "چادرینه",
    "epipodiale": "اپپودیال",
    "epipubis": "اپپوبیس",
    "epirotulian": "اپیروتولیان",
    "episcenium": "بالای صحنه",
    "episclera": "اپی‌اسکلرا",
    "episkotister": "اپیسکوتیستر",
    "epispadiac": "مربوط به اپیسپادیاس",
    "epispastic": "تاول‌آور",
    "episternalia": "استخوان‌های بالای جناغ",
    "episternum": "اپی‌استرنوم",
    "epistilbite": "اپیس‌تیلبیت",
    "Epistylis": "اپیس‌تیلیس",
    "epitimesis": "توبیخ",
    "Epitoniidae": "صدف‌های نردبانی",
    "epitrite": "پای عروضی چهار هجایی",
    "epitrochlear": "فوق قرقره‌ای",
    "epivalve": "دریچه فوقانی",
    "eponymist": "نام‌گذار",
    "epoophoron": "اپوفورون",
    "epos": "حماسه",
    "Eproboscidea": "ایپروبوسیده",
    "Eptatretidae": "مکنده ماهیان",
    "epulis": "اپولیس (تومور لثه)",
    "epulo": "اپولو",
    "epuloid": "اپولوئید",
    "epulosis": "جوش خوردن زخم",
    "equinia": "مشمشه",
    "equinovarus": "پاچنبری",
    "equipaga": "خدمه کشتی",
    "Equisetaceae": "دم‌اسبیان",
    "Equisetales": "دم‌اسب‌سانان",
    "equispaced": "با فواصل مساوی",
    "equisurface": "هم‌سطح",
    "equuleus": "پاره‌اسب (صورت فلکی)",
    "Equus": "اسب (سرده)",
    "er": "حرف ار",
    "erectopatent": "نیمه افراشته",
    "Eremochaeta": "ارموکتا",
    "erenow": "پیش از این",
    "Erethizon": "تشی آمریکایی",
    "Erethizontidae": "تشی‌های جهان جدید",
    "erewhiles": "چندی پیش",
    "erg": "ارگ (واحد کار)",
    "ergonovine": "ارگونوین",
    "eria": "اریا",
    "Ericaceae": "خلنگیان",
    "erichthus": "اریکتوس",
    "Erinaceidae": "خارپشتان",
    "Erinize": "ایرلندی کردن",
    "Eriocaulaceae": "علف‌تابیان",
    "Eriophyidae": "کنه گالی",
    "erizo": "اریکو",
    "eroteme": "نشانه سوال",
    "Erpetoichthys": "طناب‌ماهی",
    "ers": "سنگنک",
    "ersatz": "جایگزین (نامرغوب)",
    "Ertebolle": "ارتبوله",
    "erubescite": "اروبسیت (بورنیت)",
    "eruc": "کرم حشره",
    "eruca": "منداب",
    "erysipelatoid": "شبیه سرخ‌باد",
    "erysipelatous": "مربوط به سرخ‌باد",
    "erysipelous": "سرخ‌بادی",
    "Erysiphaceae": "سفیدک‌های پودری",
    "Erythrinidae": "تتراهای گرگی",
    "Erythroxylaceae": "کوکائیان",
    "es": "حرف اس",
    "escarbuncle": "لعل",
    "escargatoire": "محل پرورش حلزون",
    "esconson": "اسکون‌سن",
    "escropulo": "اسکروپولو",
    "esne": "خدمتکار",
    "esoanhydride": "ازوآنهیدرید",
    "esocataphoria": "ازوکاتافوریا",
    "Esocidae": "اردک‌ماهیان",
    "esocyclic": "درون‌حلقه‌ای",
    "esonarthex": "نارتکس داخلی",
    "espalier": "داربست درخت",
    "esplees": "محصولات زمین",
    "esquirearchy": "حکومت اشراف‌زادگان",
    "ess": "حرف اس",
    "essang": "اسنگ",
    "essed": "ارابه جنگی دوچرخ",
    "Essenis": "اسنی",
    "Essenize": "اسنی کردن",
    "Estheriidae": "استرییده",
    "estmark": "واحد پول استونی",
    "estoc": "استوک (نوعی شمشیر)",
    "eta": "اتا (حرف یونانی)",
    "Etheostomidae": "دارترماهیان (خانواده قدیمی)",
    "Etheostominae": "دارترماهیان (زیرخانواده)",
    "Etheriidae": "صدف‌های آب شیرین",
    "ethmopalatal": "پرویزنی-کامی",
    "ethmoturbinal": "پرویزنی-شاخکی",
    "ethmoturbinate": "استخوان پرویزنی شاخکی",
    "ethmovomer": "پرویزنی-تیغه‌ای",
    "Etnean": "مربوط به کوه اتنا",
    "ettle": "قصد داشتن",
    "etui": "کیف لوازم کوچک",
    "etym": "ریشه واژه",
    "Eubasidii": "یوبازیدی‌ها",
    "eucairite": "اوکاریت",
    "Eucharitidae": "زنبورهای اوخاریتید",
    "Euchite": "اوخیت (فرقه مذهبی)",
    "Euchlorophyceae": "اوکلروفیسه",
    "euchroite": "اوکروئیت",
    "euchromatic": "خوش‌رنگ",
    "euchrome": "اوکروم",
    "euchrone": "اوکرون",
    "Eucleidae": "پروانه‌های حلزونی",
    "Eucnemidae": "سوسک‌های دروغین جهنده",
    "Eucommia": "اوکومیا",
    "Eucommiaceae": "اوکومیاسه",
    "euconic": "اوکنیک",
    "Euconjugatae": "اوکونژوگاته",
    "Eucopepoda": "پاروپایان حقیقی",
    "Eucosmidae": "اوکوسمیده",
    "eucrite": "اوکریت (نوعی شهاب‌سنگ)",
    "Eucryphiaceae": "اوکریفیاسه",
    "eucryphiaceous": "مربوط به اوکریفیاسه",
    "eucryptite": "اوکریپتیت",
    "eucyclic": "او سیکلیک",
    "eudaemon": "روح نیک",
    "eudaemonia": "سعادت",
    "eudaemonic": "سعادت‌بخش",
    "eudaemonical": "مربوط به سعادت",
    "eudaemonics": "اخلاق سعادت‌گرایانه",
    "eudaemonist": "سعادت‌گرا",
    "eudaemonize": "سعادت‌مند کردن",
    "eudaemony": "سعادت",
    "eudaimonia": "خوشبختی",
    "Eudyptes": "پنگوئن‌های کاکل‌دار",
    "Euergetes": "خیرخواه",
    "euge": "آفرین",
    "Euglenaceae": "اوگلناسه",
    "Euglenidae": "اوگلنیده",
    "Euglenineae": "اوگلنیان",
    "euhemerize": "تفسیر اسطوره‌ها به وقایع تاریخی",
    "euhyostylic": "اوهیوستیلیک",
    "euhyostyly": "اوهیوستیلی",
    "eulachon": "ماهی شمع",
    "eulalia": "اولالیا (نوعی علف)",
    "eulamellibranch": "تیغه‌آبشش‌دار حقیقی",
    "Eulamellibranchia": "تیغه‌آبششان حقیقی (رده)",
    "Eulamellibranchiata": "تیغه‌آبششان حقیقی",
    "Eulimidae": "حلزون‌های اولیمید",
    "eulytite": "اولیتایت",
    "Eumenidae": "زنبورهای سفالگر",
    "eumerism": "تقسیم متقارن بدن",
    "eumerogenesis": "تولید بخش‌های مشابه",
    "eumeromorph": "اومرومورف",
    "eumeromorphic": "اومرومورفیک",
    "eumitotic": "میتوز حقیقی",
    "Eumolpides": "اومولپیدها",
    "Eumolpus": "اومولپوس",
}

with open('en2_translated.json', 'w', encoding='utf-8') as f:
    json.dump(chunk1_translations, f, ensure_ascii=False, indent=2)

